kind: pipeline
name: default

steps:
  - name: docker  
    image: plugins/docker
    settings:
      repo: docker.amodosoluciones.com/${DRONE_REPO}
      registry: docker.amodosoluciones.com
      tags: ${DRONE_COMMIT_BRANCH}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password